[tool]
[tool.poetry]
authors = ["Cori Code <coricode@yoursite.top>"]
name = "root"
version = "0.0.0"
description="Flask scraping app "
[tool.poetry.dependencies]
flask = "==1.0.2"
python = "^3.8"
bs4 = "^0.0.1"
pandas = "^1.3.2"
lxml = "^4.6.3"
